from trioapi.jdd import (
    get_jdd,
    get_elem,
    write_data,
    get_subclass,
    get_read_objects,
    get_description_as_dict,
    get_read_pb,
    get_read_sch,
    get_dis,
    get_entry_index,
)
from trioapi.jdd import SCHEME, PROBLEM
from trioapi.trustify_gen import *  # noqa: F403
from trioapi.trustify_gen_pyd import *  # noqa: F403

from trioapi.postraitement import (
    create_probe_segment,
    add_postprocess_field,
    add_probe,
    create_probe_points,
    create_probe,
    get_probe_index_by_name,
    create_field,
    create_statistics,
    add_postprocess_statistic,
    create_multiple_probes,
    add_multiple_postprocess_fields,
    add_multiple_average_statistic,
    add_multiple_standard_deviation_statistic,
)

from trioapi.discretization import change_scheme

from trioapi.interprete import (
    add_object,
    associate_to_problem,
    solve_problem,
    change_dimension,
    add_declaration_object,
    change_declaration_object,
    change_read_object,
    get_maillage,
    get_mesh,
    get_partition,
    get_scatter,
    get_dimension,
    get_domain,
    change_type_object,
    add_read_object,
)

from trioapi.attributes import (
    get_successive_attributes,
    get_attributes,
    obj_to_dict,
    obj_to_dict_type,
    dict_to_object_type,
    extract_true_type,
)

from trioapi.deletion import (
    delete_object,
    delete_read_object,
    delete_declaration_object,
)

__all__ = (
    "get_jdd",
    "get_elem",
    "write_data",
    "SCHEME",
    "PROBLEM",
    "create_probe_segment",
    "add_postprocess_field",
    "add_probe",
    "create_probe_points",
    "create_probe",
    "get_probe_index_by_name",
    "get_subclass",
    "change_scheme",
    "add_object",
    "associate_to_problem",
    "solve_problem",
    "get_successive_attributes",
    "get_attributes",
    "obj_to_dict",
    "obj_to_dict_type",
    "dict_to_object_type",
    "get_read_objects",
    "create_field",
    "create_statistics",
    "add_postprocess_statistic",
    "get_description_as_dict",
    "extract_true_type",
    "create_multiple_probes",
    "add_multiple_postprocess_fields",
    "add_multiple_average_statistic",
    "add_multiple_standard_deviation_statistic",
    "get_read_pb",
    "get_read_sch",
    "get_dis",
    "change_dimension",
    "add_declaration_object",
    "change_declaration_object",
    "change_read_object",
    "get_maillage",
    "get_mesh",
    "get_partition",
    "get_scatter",
    "get_dimension",
    "get_domain",
    "change_type_object",
    "add_read_object",
    "get_entry_index",
    "delete_object",
    "delete_read_object",
    "delete_declaration_object",
)
